import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Instrument_Sans, JetBrains_Mono, DM_Sans, Outfit } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toast"
import NextTopLoader from "nextjs-toploader";



const outfitHeading = Outfit({subsets:['latin'],variable:'--font-heading'});

const dmSans = DM_Sans({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Zaroo - Your Ultimate Travel Companion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", dmSans.variable, outfitHeading.variable)}
    >

      <body className="min-h-full flex flex-col">
        <NextTopLoader
          color="#F9954D"
          height={4}
          crawl
          showSpinner={false}
        />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
